spring.application.name=server
server.port = 8081
server.address = 0.0.0.0

# security secret
security.jwt.secret-key=very-secure-key

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5436/main_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.configuration=redis-server
spring.data.redis=6379

# AWS
aws.region=us-east-2
aws.access-key=test123
aws.secret-key=test123

aws.s3.endpoint=http://localhost:4566
aws.s3.bucket=s3-file-storage

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB